title = "DCU SpeakEasy"
baseURL = "https://www.redbrick.dcu.ie/~fraz/ispeakizi/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 3
    name = "About Us"
    url = "/aboutus"
  [[menu.header]]
    weight = 4
    name = "BESK"
    url = "/besk"
  [[menu.header]]
    weight = 5
    name = "YAP"
    url = "/yap"
  [[menu.header]]
    weight = 6
    name = "Events"
    url = "/events"
  [[menu.header]]
    weight = 7
    name = "Our Team"
    url = "/team"

  [[menu.footer]]
    weight = 3
    name = "About Us"
    url = "/aboutus"
  [[menu.footer]]
    weight = 4
    name = "BESK"
    url = "/besk"
  [[menu.footer]]
    weight = 5
    name = "YAP"
    url = "/yap"
  [[menu.footer]]
    weight = 6
    name = "Events"
    url = "/events"
  [[menu.footer]]
    weight = 7
    name = "Our Team"
    url = "/team"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"


  home = "Home"

  [params.slider]
    enable = true
    title = "Ireland’s Student Public Speaking and Communication Society"
    subtitle = "Based in Dublin City University"

  [params.aboutUs]
    enable = true
    title = "About Us"
    img = '/~fraz/ispeakizi/img/group1.png'
    values = '/~fraz/ispeakizi/img/values.png'
    italic = "We are DCU’s and Ireland’s largest public speaking and communications society and we help students to practically enhance their communication skills in a relaxed and informal setting. We are like Toastmasters (with a twist) and TEDx talks rolled into one, plus much more."
    paragraph = "In August 2016 we started the society with three members and as a way to prepare for college presentations. Since then, we have created many signature events which provide a safe and relaxed environment for students to ultimately receive constructive advice and develop their confidence."
    paragraph2 = "Speakeasy was awarded DCU’s best new society in it’s first year and it’s member base has now increases significantly year on year. Apart from our weekly events that range from impromptu Da Shpoof sessions to interactive workshops and guest speakers, we also organise two national competitions; BESK, the Best National Speaker Competition and YAP Ireland, the National Student Podcast Competition."
    paragraph3 = "As the society has grown, our mission has also grown."
    paragraph4 = "We want to help students to find their voice and to grow and adapt in different situations. In this, students will be able to create their own opportunities and compete in competitions, but most importantly compete against themselves."
    paragraph5 = "We believe that by striving to achieve these goals, our members will exceed their own expectations and gain both personal and professional growth."
    paragraph6 = "Our strong connections with industry leaders are reflected in our ethos, and we are proud have EY as Speakeasy’s main society sponsor in 2018/’19."

[params.yap]
    enable = true
    title = "/~fraz/ispeakizi/img/yap_title.png"
    img = '/~fraz/ispeakizi/img/yap.png'
    italic = "Newstalk, Off the Ball and EY have partnered with Speakeasy to launch the first national student podcast competition, YAP Ireland. "
    paragraph = "The competition is open to all registered third level students in the country, and there are four categories for students to enter:"
    paragraph2sub = "Podcasts must be no longer than 30 minutes in duration."
    head3 = "PRIZES"
    prize1 ="First prize:  Mentorship from Newstalk and Off the Ball producers and an audio production equipment package worth €400"
    prize1_img = "/~fraz/ispeakizi/img/one.png"
    prize2 = "Second prize: Podcasting equipment package worth €200"
    prize2_img = "/~fraz/ispeakizi/img/two.png"
    prize3 = "Third prize: Podcasting equipment package worth €100"
    prize3_img = "/~fraz/ispeakizi/img/three.png"
    prize4 = "All our winners will be set up with the tools to build a successful career in media!"
    head4 = "JUDGING CRITERIA"
    judge_img = '/~fraz/ispeakizi/img/judge.png'
    jc1 = "VALUE"
    jc1d = "How well does your programme entertain, inform and stimulate the audience?"
    jc2 = "PRESENTATION"
    jc2d = "How is it is presented? Is it well scripted,  polished and professional?"
    jc3 = "CREATIVITY"
    jc3d = "In terms of innovation, originality and novelty – how does it stand out?"
    jc4 = "PRODUCTION"
    jc4d = "Is your piece well-produced and quality evident?"
    twitter_link = "https://twitter.com/IrelandYap"
    facebook_link = "https://www.facebook.com/YAPIRELAND19/?ref=page_internal"
    instagram_link = "https://www.instagram.com/yap_ireland/"
    partner = "/~fraz/ispeakizi/img/newstalk.png"

[params.besk]
    enable = true
    title = "BESK"
    img = '/~fraz/ispeakizi/img/group2.png'
    italic = "This is Speakeasy DCU’s first year running BESK, our student best speaker competition. Students have the opportunity to speak about a topic that they’re passionate about for up to 7 minutes."
    paragraph = "In August 2016 we started the society with three members and as a way to prepare for college presentations. Since then, we have created many signature events which provide a safe and relaxed environment for students to ultimately receive constructive advice and develop their confidence."
    paragraph2 = "Blurb about National Student Speaker Competition/ Competition format"
    paragraph3 = "Date/Time/Location for Qualifier Rounds in each college & contacts for entry"
    paragraph4 = ""
    paragraph5 = ""
    paragraph6 = ""
    partnership = ""
    videolink = ""

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We host amazing events"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    img = ""
    [params.feature.button]
      caption = "View Events"
      url = "/events"

  [params.call]
    enable = true
    title = "We are constantly loooking for new people to join Speak Easy."
    paragraph = "If you're interested you can get in contact with our committee and we'll help you join."
    [params.call.button]
    url = 'mailto:committee@speakeasy.dcu.ie'
    text = 'Email Committee'
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Get in touch with us by filling out the contact form below!"
    [params.contact.form]
      name = "Your name *"
      email = "Your email *"
      phone = "Your phone"
      message = "Your message *"
      button = "Send message"
